name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      deployments: write
  
    steps:
      - uses: chrnorm/deployment-action@v2
        
      - name: deploy
        id: deploy
        with:
          token: '${{ github.token }}'
          environment-url: http://my-app-url.com
          environment: development
          state: 'success'
          
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'